### ISSUE TITLE
Uso desnecessário/incorreto de herança

### ISSUE THREAD

**Issue by AndreaInfUFSM** [elc117/java02-2022b-giovannircl#1]
Você está usando `extends Main` na classe `display`, o que significa herança da classe `Main`.  Embora funcione, no caso em questão, é um uso desnecessário/incorreto de herança.

**Comment by giovannircl** [comment]
Pois é eu fiquei confuso de certa forma em como eu estruturaria para rodar o código usando os dois arquivos, busquei sobre e achei o 'Extends', porém não fui muito afundo e só vi que tinha funcionado.
